In [1]:
import random
import collections
from fractions import Fraction
import pandas as pd
import itertools

In [2]:
hands_df = pd.read_csv('../Extra_Storage/UPDATED_ALL_HAND_OPTIONS.csv')  
hands_df = hands_df.drop(columns=['Unnamed: 0', 'Unnamed: 0.1'])

In [3]:
discard_list = [0,1,2,3,4]
all_discard_options = []
for L in range(len(discard_list) + 1):
    for subset in itertools.combinations(discard_list, L):
        discard_option = list(subset)
        all_discard_options.append(discard_option)
        
all_discard_options.pop(0)

[]

In [4]:
all_discard_options

[[0],
 [1],
 [2],
 [3],
 [4],
 [0, 1],
 [0, 2],
 [0, 3],
 [0, 4],
 [1, 2],
 [1, 3],
 [1, 4],
 [2, 3],
 [2, 4],
 [3, 4],
 [0, 1, 2],
 [0, 1, 3],
 [0, 1, 4],
 [0, 2, 3],
 [0, 2, 4],
 [0, 3, 4],
 [1, 2, 3],
 [1, 2, 4],
 [1, 3, 4],
 [2, 3, 4],
 [0, 1, 2, 3],
 [0, 1, 2, 4],
 [0, 1, 3, 4],
 [0, 2, 3, 4],
 [1, 2, 3, 4],
 [0, 1, 2, 3, 4]]

In [5]:
card_deck = []

i = 2
j = 1
while i < 15 and j < 5:
    card = []
    card.append(i)
    
    if j == 1:
        card.append('Heart')
    elif j == 2:
        card.append('Diamond')
    elif j == 3:
        card.append('Spade')
    elif j == 4:
        card.append('Club')
    
    if i == 2:
        card.append('Y')
    else:
        card.append('N')
        
    if i == 14:
        j = j + 1
        i = 1
    
    card_deck.append(card)
    i = i + 1

In [6]:
i = 1
j = 52
card_hand = []

while i < 6:
    x = random.randrange(0, j)    
    dealt_card = card_deck.pop(x)
    card_hand.append(dealt_card)
    i = i + 1
    j = j - 1
    
first_dealt_hand = card_hand
first_dealt_hand

[[3, 'Heart', 'N'],
 [12, 'Spade', 'N'],
 [11, 'Spade', 'N'],
 [3, 'Club', 'N'],
 [11, 'Heart', 'N']]

In [7]:
string_first_hand = []
for card in first_dealt_hand:
    string_first_hand.append(str(card))

string_first_hand

["[3, 'Heart', 'N']",
 "[12, 'Spade', 'N']",
 "[11, 'Spade', 'N']",
 "[3, 'Club', 'N']",
 "[11, 'Heart', 'N']"]

In [8]:
# potential_discarded_card
all_discard_options

complete_discard_list = []

for item in all_discard_options:
    discard_string = ''

    for mini_item in item:
        temp_string = str(mini_item)
        discard_string = discard_string + temp_string
        
    complete_discard_list.append(discard_string)
    
complete_discard_list

['0',
 '1',
 '2',
 '3',
 '4',
 '01',
 '02',
 '03',
 '04',
 '12',
 '13',
 '14',
 '23',
 '24',
 '34',
 '012',
 '013',
 '014',
 '023',
 '024',
 '034',
 '123',
 '124',
 '134',
 '234',
 '0123',
 '0124',
 '0134',
 '0234',
 '1234',
 '01234']

In [9]:
# test_hand = ["[2, 'Heart', 'Y']","[10, 'Club', 'N']","[5,'Diamond','N']"]

complete_discard_odds_df_list = []

for discard_option in complete_discard_list:
    test_discarded_card_position_list = [*discard_option]

    saved_hand = []
    for card in first_dealt_hand:
        saved_hand.append(card)

    temp_hand = saved_hand

    
    k = 0
    discarded_cards = []
    for item in test_discarded_card_position_list:
        num_item = int(item)
        card_position = num_item - k
        discard = temp_hand.pop(card_position)
        discarded_cards.append(discard)
        k = k + 1

    string_hand = []    
    for item in temp_hand:
        new_item = str(item)
        string_hand.append(new_item)

        
    if len(string_hand) == 1:
        test_odds_df = hands_df[hands_df.isin([string_hand[0]]).any(axis=1)]
    elif len(string_hand) == 2:
        test_odds_df = hands_df[hands_df.isin([string_hand[0]]).any(axis=1) & hands_df.isin([string_hand[1]]).any(axis=1)]
    elif len(string_hand) == 3:
        test_odds_df = hands_df[hands_df.isin([string_hand[0]]).any(axis=1) & hands_df.isin([string_hand[1]]).any(axis=1) & hands_df.isin([string_hand[2]]).any(axis=1)]
    elif len(string_hand) == 4:
        test_odds_df = hands_df[hands_df.isin([string_hand[0]]).any(axis=1) & hands_df.isin([string_hand[1]]).any(axis=1) & hands_df.isin([string_hand[2]]).any(axis=1) & hands_df.isin([string_hand[3]]).any(axis=1)]
    elif len(string_hand) == 0:
        test_odds_df = hands_df.loc[~hands_df.isin(string_first_hand).any(axis=1)]


    test_odds_summary_df = pd.DataFrame(test_odds_df['Result'].value_counts())

    test = test_odds_summary_df['Result'].sum()
    
    temp_odds_list = test_odds_summary_df['Result'].tolist()

    new_list = []
    for item in temp_odds_list:
        new_list.append("{:.5f}".format((item / test) * 100))

    test_odds_summary_df['Percentage'] = new_list

    win_total_df = test_odds_summary_df
    
    if "['Loss']" in win_total_df.index:
        win_total_df = win_total_df.drop(index=("['Loss']"))

    win_total = win_total_df['Result'].sum()

    test_odds_summary_df.loc['Win', :] = [win_total,("{:.5f}".format((win_total / test) * 100))]

    
    test_odds_summary_df['Discard Positions'] = discard_option

    discarded_cards_string = str(discarded_cards)
    test_odds_summary_df['Discard Cards'] = discarded_cards_string

    complete_discard_odds_df_list.append(test_odds_summary_df)

complete_discard_odds_df = pd.concat(complete_discard_odds_df_list)

In [10]:
# complete_discard_odds_df
final_complete_discard_odds_df = complete_discard_odds_df.drop(index=("['Loss']"))
final_complete_discard_odds_df['Percentage'] = final_complete_discard_odds_df['Percentage'].astype(float)
final_complete_discard_odds_df = final_complete_discard_odds_df.sort_values(by=['Percentage'], ascending = False)
print(first_dealt_hand)
final_complete_discard_odds_df.head(50)

[[3, 'Heart', 'N'], [12, 'Spade', 'N'], [11, 'Spade', 'N'], [3, 'Club', 'N'], [11, 'Heart', 'N']]

/var/folders/2d/w0_y9zt547v2y0371_wclbcm0000gn/T/ipykernel_22144/61141876.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_complete_discard_odds_df['Percentage'] = final_complete_discard_odds_df['Percentage'].astype(float)

,Result,Percentage,Discard Positions,Discard Cards
Win,6400.0,32.65306,013,"[[3, 'Heart', 'N'], [12, 'Spade', 'N'], [3, 'C..."
Win,6400.0,32.65306,124,"[[12, 'Spade', 'N'], [11, 'Spade', 'N'], [11, ..."
['Three of a Kind'],5280.0,26.93878,013,"[[3, 'Heart', 'N'], [12, 'Spade', 'N'], [3, 'C..."
['Three of a Kind'],5280.0,26.93878,124,"[[12, 'Spade', 'N'], [11, 'Spade', 'N'], [11, ..."
Win,276.0,23.46939,12,"[[12, 'Spade', 'N'], [11, 'Spade', 'N']]"
Win,276.0,23.46939,14,"[[12, 'Spade', 'N'], [11, 'Heart', 'N']]"
Win,276.0,23.46939,24,"[[11, 'Spade', 'N'], [11, 'Heart', 'N']]"
Win,276.0,23.46939,03,"[[3, 'Heart', 'N'], [3, 'Club', 'N']]"
Win,276.0,23.46939,01,"[[3, 'Heart', 'N'], [12, 'Spade', 'N']]"
Win,276.0,23.46939,13,"[[12, 'Spade', 'N'], [3, 'Club', 'N']]"
Win,316012.0,20.60134,01234,"[[3, 'Heart', 'N'], [12, 'Spade', 'N'], [11, '..."
['Three of a Kind'],240.0,20.40816,03,"[[3, 'Heart', 'N'], [3, 'Club', 'N']]"
['Three of a Kind'],240.0,20.40816,13,"[[12, 'Spade', 'N'], [3, 'Club', 'N']]"
['Three of a Kind'],240.0,20.40816,24,"[[11, 'Spade', 'N'], [11, 'Heart', 'N']]"
['Three of a Kind'],240.0,20.40816,12,"[[12, 'Spade', 'N'], [11, 'Spade', 'N']]"
['Three of a Kind'],240.0,20.40816,14,"[[12, 'Spade', 'N'], [11, 'Heart', 'N']]"
['Three of a Kind'],240.0,20.40816,01,"[[3, 'Heart', 'N'], [12, 'Spade', 'N']]"
Win,8.0,16.66667,1,"[[12, 'Spade', 'N']]"
['Full House'],8.0,16.66667,1,"[[12, 'Spade', 'N']]"
Win,39366.0,15.75270,0123,"[[3, 'Heart', 'N'], [12, 'Spade', 'N'], [11, '..."
Win,39366.0,15.75270,0134,"[[3, 'Heart', 'N'], [12, 'Spade', 'N'], [3, 'C..."
['Three of a Kind'],239596.0,15.61966,01234,"[[3, 'Heart', 'N'], [12, 'Spade', 'N'], [11, '..."
Win,38355.0,15.34814,0234,"[[3, 'Heart', 'N'], [11, 'Spade', 'N'], [3, 'C..."
Win,36333.0,14.53902,0124,"[[3, 'Heart', 'N'], [12, 'Spade', 'N'], [11, '..."
Win,36333.0,14.53902,1234,"[[12, 'Spade', 'N'], [11, 'Spade', 'N'], [3, '..."
Win,2749.0,14.02551,034,"[[3, 'Heart', 'N'], [3, 'Club', 'N'], [11, 'He..."
Win,2480.0,12.65306,023,"[[3, 'Heart', 'N'], [11, 'Spade', 'N'], [3, 'C..."
Win,6.0,12.50000,0,"[[3, 'Heart', 'N']]"
['Three of a Kind'],6.0,12.50000,0,"[[3, 'Heart', 'N']]"
Win,6.0,12.50000,3,"[[3, 'Club', 'N']]"
['Three of a Kind'],6.0,12.50000,3,"[[3, 'Club', 'N']]"
Win,6.0,12.50000,2,"[[11, 'Spade', 'N']]"
['Three of a Kind'],6.0,12.50000,4,"[[11, 'Heart', 'N']]"
Win,6.0,12.50000,4,"[[11, 'Heart', 'N']]"
['Three of a Kind'],6.0,12.50000,2,"[[11, 'Spade', 'N']]"
['Three of a Kind'],30356.0,12.14726,0124,"[[3, 'Heart', 'N'], [12, 'Spade', 'N'], [11, '..."
['Three of a Kind'],30356.0,12.14726,1234,"[[12, 'Spade', 'N'], [11, 'Spade', 'N'], [3, '..."
['Three of a Kind'],30077.0,12.03561,0234,"[[3, 'Heart', 'N'], [11, 'Spade', 'N'], [3, 'C..."
['Three of a Kind'],29984.0,11.99840,0134,"[[3, 'Heart', 'N'], [12, 'Spade', 'N'], [3, 'C..."
['Three of a Kind'],29984.0,11.99840,0123,"[[3, 'Heart', 'N'], [12, 'Spade', 'N'], [11, '..."
Win,2140.0,10.91837,123,"[[12, 'Spade', 'N'], [11, 'Spade', 'N'], [3, '..."
Win,1840.0,9.38776,024,"[[3, 'Heart', 'N'], [11, 'Spade', 'N'], [11, '..."
Win,1840.0,9.38776,234,"[[11, 'Spade', 'N'], [3, 'Club', 'N'], [11, 'H..."
Win,1840.0,9.38776,012,"[[3, 'Heart', 'N'], [12, 'Spade', 'N'], [11, '..."
Win,1840.0,9.38776,134,"[[12, 'Spade', 'N'], [3, 'Club', 'N'], [11, 'H..."
Win,1840.0,9.38776,014,"[[3, 'Heart', 'N'], [12, 'Spade', 'N'], [11, '..."
['Three of a Kind'],1720.0,8.77551,012,"[[3, 'Heart', 'N'], [12, 'Spade', 'N'], [11, '..."
['Three of a Kind'],1720.0,8.77551,234,"[[11, 'Spade', 'N'], [3, 'Club', 'N'], [11, 'H..."
['Three of a Kind'],1720.0,8.77551,024,"[[3, 'Heart', 'N'], [11, 'Spade', 'N'], [11, '..."
['Three of a Kind'],1720.0,8.77551,134,"[[12, 'Spade', 'N'], [3, 'Club', 'N'], [11, 'H..."

In [11]:
# final_complete_discard_odds_df.loc[final_complete_discard_odds_df['Discard Positions'] == '3']