In [1]:
import pandas as pd
import re
import collections
from fractions import Fraction

In [2]:
hands_df = pd.read_csv('../Extra_Storage/ALL_HAND_OPTIONS.csv')  
hands_df

,Unnamed: 0,0,1,2,3,4
0,0,"[2, 'Heart', 'Y']","[3, 'Heart', 'N']","[4, 'Heart', 'N']","[5, 'Heart', 'N']","[6, 'Heart', 'N']"
1,1,"[2, 'Heart', 'Y']","[3, 'Heart', 'N']","[4, 'Heart', 'N']","[5, 'Heart', 'N']","[7, 'Heart', 'N']"
2,2,"[2, 'Heart', 'Y']","[3, 'Heart', 'N']","[4, 'Heart', 'N']","[5, 'Heart', 'N']","[8, 'Heart', 'N']"
3,3,"[2, 'Heart', 'Y']","[3, 'Heart', 'N']","[4, 'Heart', 'N']","[5, 'Heart', 'N']","[9, 'Heart', 'N']"
4,4,"[2, 'Heart', 'Y']","[3, 'Heart', 'N']","[4, 'Heart', 'N']","[5, 'Heart', 'N']","[10, 'Heart', 'N']"
...,...,...,...,...,...,...
2598955,2598955,"[9, 'Club', 'N']","[10, 'Club', 'N']","[11, 'Club', 'N']","[12, 'Club', 'N']","[14, 'Club', 'N']"
2598956,2598956,"[9, 'Club', 'N']","[10, 'Club', 'N']","[11, 'Club', 'N']","[13, 'Club', 'N']","[14, 'Club', 'N']"
2598957,2598957,"[9, 'Club', 'N']","[10, 'Club', 'N']","[12, 'Club', 'N']","[13, 'Club', 'N']","[14, 'Club', 'N']"
2598958,2598958,"[9, 'Club', 'N']","[11, 'Club', 'N']","[12, 'Club', 'N']","[13, 'Club', 'N']","[14, 'Club', 'N']"
2598959,2598959,"[10, 'Club', 'N']","[11, 'Club', 'N']","[12, 'Club', 'N']","[13, 'Club', 'N']","[14, 'Club', 'N']"

In [3]:
hands_df['Result'] = ''
hands_df

,Unnamed: 0,0,1,2,3,4,Result
0,0,"[2, 'Heart', 'Y']","[3, 'Heart', 'N']","[4, 'Heart', 'N']","[5, 'Heart', 'N']","[6, 'Heart', 'N']",
1,1,"[2, 'Heart', 'Y']","[3, 'Heart', 'N']","[4, 'Heart', 'N']","[5, 'Heart', 'N']","[7, 'Heart', 'N']",
2,2,"[2, 'Heart', 'Y']","[3, 'Heart', 'N']","[4, 'Heart', 'N']","[5, 'Heart', 'N']","[8, 'Heart', 'N']",
3,3,"[2, 'Heart', 'Y']","[3, 'Heart', 'N']","[4, 'Heart', 'N']","[5, 'Heart', 'N']","[9, 'Heart', 'N']",
4,4,"[2, 'Heart', 'Y']","[3, 'Heart', 'N']","[4, 'Heart', 'N']","[5, 'Heart', 'N']","[10, 'Heart', 'N']",
...,...,...,...,...,...,...,...
2598955,2598955,"[9, 'Club', 'N']","[10, 'Club', 'N']","[11, 'Club', 'N']","[12, 'Club', 'N']","[14, 'Club', 'N']",
2598956,2598956,"[9, 'Club', 'N']","[10, 'Club', 'N']","[11, 'Club', 'N']","[13, 'Club', 'N']","[14, 'Club', 'N']",
2598957,2598957,"[9, 'Club', 'N']","[10, 'Club', 'N']","[12, 'Club', 'N']","[13, 'Club', 'N']","[14, 'Club', 'N']",
2598958,2598958,"[9, 'Club', 'N']","[11, 'Club', 'N']","[12, 'Club', 'N']","[13, 'Club', 'N']","[14, 'Club', 'N']",
2598959,2598959,"[10, 'Club', 'N']","[11, 'Club', 'N']","[12, 'Club', 'N']","[13, 'Club', 'N']","[14, 'Club', 'N']",

In [5]:
win_indicator_list = []

for i in range(2598960):

    temp_list = [hands_df['0'][i],hands_df['1'][i],hands_df['2'][i],hands_df['3'][i],hands_df['4'][i]]

    hand = []
    for item in temp_list:
        new_item = re.findall('[a-zA-Z0-9]+',item)
        new_item[0] = int(new_item[0])
        hand.append(new_item)


        
    winning_hand_indicator = []

    # Get card numbers and sort them to make it easier to identify winning patters
    wildcard_position_indicator = 0
    wildcard_positions = []

    for third in hand:

        if third[2] == 'Y':
            wildcard_positions.append(wildcard_position_indicator)

        wildcard_position_indicator = wildcard_position_indicator + 1

    wildcard_counter = len(wildcard_positions)
#         print(wildcard_positions)


    # Get card numbers and sort them to make it easier to identify winning patters
    final_hand_numbers = []
    final_hand_numbers_no_wildcards = []

    for first in hand:
        final_hand_numbers.append(first[0])
        if first[0] == 2:
            continue
        else:
            final_hand_numbers_no_wildcards.append(first[0])

    # i = 0
    # if len(wildcard_positions) > 0:
    #     for i in range(len(wildcard_positions)):
    #         final_hand_numbers_no_wildcards.pop(wildcard_positions[i])
    #         i = i + 1

    final_hand_numbers.sort()
    final_hand_numbers_no_wildcards.sort()
#         print(final_hand_numbers)
#         print(final_hand_numbers_no_wildcards)


    # Get card suits and sort them to make it easier to identify winning patters
    final_hand_suits = []
    final_hand_suits_no_wildcards = []

    for second in hand:
        final_hand_suits.append(second[1])

        if second[0] == 2:
            continue
        else:
            final_hand_suits_no_wildcards.append(second[1])


    #     final_hand_suits_no_wildcards.append(second[1])

    # if len(wildcard_positions) > 0:
    #     for i in range(len(wildcard_positions)):
    #         final_hand_suits_no_wildcards.pop(wildcard_positions[i])


    final_hand_suits.sort()
#         print(final_hand_suits)
#         print(final_hand_suits_no_wildcards)



    # Four Dueces - 200

    if wildcard_counter == 4:
        winning_hand_indicator.append('Four Deuces')




    # Five of a Kind - 10

    card_number_count = collections.Counter(final_hand_numbers_no_wildcards)
    if card_number_count[card_number_count.most_common(1)[0][0]] + len(wildcard_positions) == 5:
        winning_hand_indicator.append('Five of a Kind')


    # Four of a Kind - 4

    card_number_count = collections.Counter(final_hand_numbers_no_wildcards)
    if card_number_count[card_number_count.most_common(1)[0][0]] + len(wildcard_positions) == 4:
        winning_hand_indicator.append('Four of a Kind')


    # Full House - 3

    no_wildcard_numbers_set = set(final_hand_numbers_no_wildcards)

    card_number_count = collections.Counter(final_hand_numbers_no_wildcards)
    if card_number_count[card_number_count.most_common(1)[0][0]] + len(wildcard_positions) == 3 and len(no_wildcard_numbers_set) == 2:
        winning_hand_indicator.append('Full House')


    # Flush - 2
    suits_set = set(final_hand_suits)
    no_wildcard_suits_set = set(final_hand_suits_no_wildcards)

    if len(suits_set) == 1:
        winning_hand_indicator.append('Flush')

    elif len(wildcard_positions) > 0:
        unique_suits_frequency = []
        for item in suits_set:
            unique_suits_frequency.append(final_hand_suits.count(item))
            if final_hand_suits.count(item) == len(final_hand_suits_no_wildcards) and len(no_wildcard_suits_set) == 1:
                winning_hand_indicator.append('Flush')
#             print(unique_suits_frequency)


    # Straight with Ace High - 2
    i = 0
    j = 1
    temp_wildcard_counter = wildcard_counter
    for i in range(len(final_hand_numbers_no_wildcards)):
        if wildcard_counter == 4:
            break
        if final_hand_numbers_no_wildcards[j] - final_hand_numbers_no_wildcards[i] == 1:
            if j == (len(final_hand_numbers_no_wildcards) - 1):
                winning_hand_indicator.append('Straight')
                break
            else:
                i = i + 1
                j = j + 1
                continue
        elif final_hand_numbers_no_wildcards[j] - final_hand_numbers_no_wildcards[i] == 2 and temp_wildcard_counter == 1:
            if j == (len(final_hand_numbers_no_wildcards) - 1):
                winning_hand_indicator.append('Straight')
                break
            else:
                i = i + 1
                j = j + 1
                temp_wildcard_counter = temp_wildcard_counter - 1
                continue
        elif final_hand_numbers_no_wildcards[j] - final_hand_numbers_no_wildcards[i] == 3 and temp_wildcard_counter == 2:
            if j == (len(final_hand_numbers_no_wildcards) - 1):
                winning_hand_indicator.append('Straight')
                break
            else:
                i = i + 1
                j = j + 1
                temp_wildcard_counter = temp_wildcard_counter - 2
                continue
        else:
            i = i + 1
            j = j + 1
            break


    if 14 in final_hand_numbers_no_wildcards:
        aces_low_hand_numbers_list = []
        for item in final_hand_numbers_no_wildcards:
            if item == 14:
                aces_low_hand_numbers_list.insert(0, 1)
            else:
                aces_low_hand_numbers_list.append(item)

        # Straight with Ace Low - 2
        i = 0
        j = 1
        temp_wildcard_counter = wildcard_counter
        for i in range(len(aces_low_hand_numbers_list)):
            if wildcard_counter == 4:
                break
            if aces_low_hand_numbers_list[j] - aces_low_hand_numbers_list[i] == 1:
                if j == (len(aces_low_hand_numbers_list) - 1):
                    winning_hand_indicator.append('Straight')
                    break
                else:
                    i = i + 1
                    j = j + 1
                    continue
            elif aces_low_hand_numbers_list[j] - aces_low_hand_numbers_list[i] == 2 and temp_wildcard_counter == 1:
                if j == (len(aces_low_hand_numbers_list) - 1):
                    winning_hand_indicator.append('Straight')
                    break
                else:
                    i = i + 1
                    j = j + 1
                    temp_wildcard_counter = temp_wildcard_counter - 1
                    continue
            elif aces_low_hand_numbers_list[j] - aces_low_hand_numbers_list[i] == 3 and temp_wildcard_counter == 2:
                if j == (len(aces_low_hand_numbers_list) - 1):
                    winning_hand_indicator.append('Straight')
                    break
                else:
                    i = i + 1
                    j = j + 1
                    temp_wildcard_counter = temp_wildcard_counter - 2
                    continue
            else:
                i = i + 1
                j = j + 1
                break

            
    # Three of a Kind - 1

    card_number_count = collections.Counter(final_hand_numbers_no_wildcards)
    if card_number_count[card_number_count.most_common(1)[0][0]] + len(wildcard_positions) == 3:
        winning_hand_indicator.append('Three of a Kind')


    # Straight Flush - 8

    if 'Flush' in winning_hand_indicator and 'Straight' in winning_hand_indicator:
        winning_hand_indicator.remove('Flush')
        winning_hand_indicator.remove('Straight')
        winning_hand_indicator.append('Straight Flush')


    # Royal Flush with No Duece - 300

    if 'Straight Flush' in winning_hand_indicator:
        if 14 in final_hand_numbers_no_wildcards and 10 in final_hand_numbers_no_wildcards and wildcard_counter == 0:
            winning_hand_indicator.remove('Straight Flush')
            winning_hand_indicator.append('Royal Flush')


    # Royal Flush with Duece - 20

    if 'Straight Flush' in winning_hand_indicator:
        royal_flush_numbers = [10,11,12,13,14]
        royal_flush_counter = 0
        for number in final_hand_numbers_no_wildcards:
            if number in royal_flush_numbers:
                royal_flush_counter = royal_flush_counter + 1
                continue
            else:
                break
        if royal_flush_counter == len(final_hand_numbers_no_wildcards):
            winning_hand_indicator.remove('Straight Flush')
            winning_hand_indicator.append('Royal Flush with Duece')



    # Final Decision
    if len(winning_hand_indicator) == 0:
        winning_hand_indicator.append('Loss')

#         print(winning_hand_indicator)

    win_indicator_list.append(winning_hand_indicator)


# all_odds_list = hands_df['Result'].to_list()
final_odds_list = []

for item in win_indicator_list:
    if len(item) > 1:
        if 'Royal Flush' in item:
            final_odds_list.append(['Royal Flush'])
        elif 'Four Deuces' in item:
            final_odds_list.append(['Four Deuces'])
        elif 'Royal Flush with Duece' in item:
            final_odds_list.append(['Royal Flush with Duece'])
        elif 'Five of a Kind' in item:
            final_odds_list.append(['Five of a Kind'])
        elif 'Straight Flush' in item:
            final_odds_list.append(['Straight Flush'])
        elif 'Four of a Kind' in item:
            final_odds_list.append(['Four of a Kind'])
        elif 'Full House' in item:
            final_odds_list.append(['Full House'])
        elif 'Flush' in item:
            final_odds_list.append(['Flush'])
        elif 'Straight' in item:
            final_odds_list.append(['Straight'])
        elif 'Full House' in item:
            final_odds_list.append(['Full House'])
    else:
        final_odds_list.append(item)

    
hands_df['Result'] = final_odds_list

In [10]:
hands_df.to_csv('../Extra_Storage/UPDATED_ALL_HAND_OPTIONS.csv')
# hands_df = pd.read_csv('../Extra_Storage/UPDATED_ALL_HAND_OPTIONS.csv')

In [6]:
hands_df

,Unnamed: 0,0,1,2,3,4,Result
0,0,"[2, 'Heart', 'Y']","[3, 'Heart', 'N']","[4, 'Heart', 'N']","[5, 'Heart', 'N']","[6, 'Heart', 'N']",[Straight Flush]
1,1,"[2, 'Heart', 'Y']","[3, 'Heart', 'N']","[4, 'Heart', 'N']","[5, 'Heart', 'N']","[7, 'Heart', 'N']",[Straight Flush]
2,2,"[2, 'Heart', 'Y']","[3, 'Heart', 'N']","[4, 'Heart', 'N']","[5, 'Heart', 'N']","[8, 'Heart', 'N']",[Flush]
3,3,"[2, 'Heart', 'Y']","[3, 'Heart', 'N']","[4, 'Heart', 'N']","[5, 'Heart', 'N']","[9, 'Heart', 'N']",[Flush]
4,4,"[2, 'Heart', 'Y']","[3, 'Heart', 'N']","[4, 'Heart', 'N']","[5, 'Heart', 'N']","[10, 'Heart', 'N']",[Flush]
...,...,...,...,...,...,...,...
2598955,2598955,"[9, 'Club', 'N']","[10, 'Club', 'N']","[11, 'Club', 'N']","[12, 'Club', 'N']","[14, 'Club', 'N']",[Flush]
2598956,2598956,"[9, 'Club', 'N']","[10, 'Club', 'N']","[11, 'Club', 'N']","[13, 'Club', 'N']","[14, 'Club', 'N']",[Flush]
2598957,2598957,"[9, 'Club', 'N']","[10, 'Club', 'N']","[12, 'Club', 'N']","[13, 'Club', 'N']","[14, 'Club', 'N']",[Flush]
2598958,2598958,"[9, 'Club', 'N']","[11, 'Club', 'N']","[12, 'Club', 'N']","[13, 'Club', 'N']","[14, 'Club', 'N']",[Flush]
2598959,2598959,"[10, 'Club', 'N']","[11, 'Club', 'N']","[12, 'Club', 'N']","[13, 'Club', 'N']","[14, 'Club', 'N']",[Royal Flush]

In [7]:
all_odds_df = pd.DataFrame(hands_df['Result'].value_counts())
all_odds_df
# new_list = []

# result['Percentage'] = new_list
# result.sort_values('Odds', ascending = False)
# # result = result.drop([Loss])

                           Result
[Loss]                    2119728
[Three of a Kind]          367476
[Straight]                  52476
[Four of a Kind]            32164
[Flush]                     12828
[Full House]                12672
[Straight Flush]              784
[Five of a Kind]              624
[Royal Flush with Duece]      156
[Four Deuces]                  48
[Royal Flush]                   4

In [8]:
testing_df = all_odds_df

test2 = testing_df['Result'].sum()
testing_df = testing_df.drop(index=("['Loss']"))
test3 = testing_df['Result'].sum()


print(test2)
print(test3)



testing_df.loc['Win', :] = [test3,("{:.5f}%".format((test3 / test2) * 100))]
testing_df

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas/_libs/hashtable_class_helper.pxi", line 5231, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'

TypeError: unhashable type: 'list'

In [10]:
testing_df

[478224, '18.40059%']

In [9]:
test = all_odds_df['Result'].sum()

odds_list = all_odds_df['Result'].tolist()

new_list = []
for item in odds_list:
    new_list.append("{:.5f}%".format((item / test) * 100))

all_odds_df['Percentage'] = new_list
all_odds_df

                           Result Percentage
[Loss]                    2119728  81.56062%
[Three of a Kind]          367476  14.13935%
[Straight]                  52476   2.01912%
[Four of a Kind]            32164   1.23757%
[Flush]                     12828   0.49358%
[Full House]                12672   0.48758%
[Straight Flush]              784   0.03017%
[Five of a Kind]              624   0.02401%
[Royal Flush with Duece]      156   0.00600%
[Four Deuces]                  48   0.00185%
[Royal Flush]                   4   0.00015%